### ISSUE TITLE
Требования к проекту

### ISSUE THREAD

**Issue by iggosha** [iggosha/SiteLab#1]
Проект должен иметь осмысленный сценарий (например, сайт
учителя математики, истории, портфолио, сайт, посвященный работе
своего научного направления, различные интерактивные web-приложения
для оценки результатов проведения ГТО, для работы с таблицей
Менделеева, для демонстраций возможностей человеческого организма,
интерактивные квесты или игры с выбором стран и их столиц, тесты,
головоломки, интерактивные галереи и много другое).
Проект сайта должен содержать минимум две страницы, между
которыми реализованы переходы, а также использованы различные
HTML-элементы, каскадные таблицы стилей и технологии языка
JavaScript.

Итак, требования:

- [x] #2
- [x] #3
- [x] Использование HTML
- [x] Использование CSS
- [x] Использование JS

**Comment by iggosha** [comment]
Примерный план:

- [x] Определение темы
- [x] Удаление лишних элементов
- [x] Поиск контента (картинок, текста, ...)
- [x] Создание текстового наполнения
- [x] Создание структуры первой страницы
- [x] Создание структуры второй страницы
- [x] Создание оформления с помощью стилей
- [x] Использование JS

**Comment by SeReRaGuy** [comment]
Суши

**Comment by SeReRaGuy** [comment]
Хуюши
